#!/bin/bash

/usr/local/bin/docker-compose -f docker-compose.yml run -v ~/radiant/sen2cor_test_data/aux_data:/Sen2Cor-02.05.05-Linux64/lib/python2.7/site-packages/sen2cor/aux_data --rm l2a /src/wrapper.sh "$@"
echo 'done'
